apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-simulation-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-simulation-server
  template:
    metadata:
      name: my-simulation-server-pod
      labels:
        app: my-simulation-server
    spec:
      containers:
        - name: simulation-server
          image: contest73-backend.kr.ncr.ntruss.com/contest73-simulation:latest
          ports:
            - containerPort: 8001
          env:
            - name: NCP_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: ncp-access-key
            - name: NCP_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: ncp-secret-key
            - name: AI_SERVER_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: ai-server-base-url
            - name: SPRING_SERVER_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: spring-server-base-url
            - name: CLIMATE_DATA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: climate-data-api-key
            - name: DISASTER_DATA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: disaster-data-api-key
            - name: MYSQL_HOST
              value: "my-mysql-service"
            - name: MYSQL_PORT
              value: "13006"
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: my-simulation-server-service
spec:
  selector:
    app: my-simulation-server
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
